### PR TITLE
Fixed encode decode issue

### LINKED ISSUE #1: Fix encode / decode mode discrepancy
Currently, if one wants to practice decoding symbols, the user must enter encode as the mode as that is what the executable must do internally. It should be more intuitive for the user, even if the internals are a bit more complicated.

### PR DESCRIPTION
**Pull request by chrisljiang**
Fixes #1 by using the intuitive meanings for the user when parsing command line arguments and printing chosen mode of operation, but then switches the stored mode of operation for internal use as the user will not need to see the mode again at this point.

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -59,6 +59,12 @@ int main(int argc, char *argv[]) {
     parseArgs(argc, argv, codeType, modeType);
     printArgs(codeType, modeType);
 
+    if (modeType == encode) {
+        modeType = decode;
+    } else if (modeType == decode) {
+        modeType = encode;
+    }
```
Comment (chrisljiang) [inline main.cpp:66]: Currently `else if` is not necessary, but good for future expansion.
